# Generated by Django 2.1.5 on 2019-02-17 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 2, 17, 15, 23, 15, 251182, tzinfo=utc))),
                ('Salary_Type', models.CharField(choices=[('ALLOWANCE', 'Pay Allowances'), ('Salary', 'Monthly Salary'), ('Advance', 'Pay Advances'), ('Commission', 'Pay Commission')], default='SALARY', max_length=12)),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='Month of Pay', max_length=12)),
                ('Amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 2, 17, 15, 23, 15, 252264, tzinfo=utc))),
                ('PaymentMadeTo', models.CharField(default='Canon', max_length=100)),
                ('ReasonForPayment', models.CharField(choices=[('Mechanic', 'Car Repairing'), ('WaterBills', 'Water Bills'), ('Electricity', 'Electricity Bills'), ('URA', 'Paying Revenue')], max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('ReceivedBy', models.CharField(default='receptionist', max_length=100)),
                ('ApprovedBy', models.CharField(default='receptionist', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FistName', models.CharField(default='1st name', max_length=150)),
                ('SecondName', models.CharField(default='2nd name', max_length=150)),
                ('Salary', models.IntegerField(default=0)),
                ('Role', models.CharField(choices=[('Developers', 'ICT'), ('Receptionist', 'Rec'), ('Director', 'DIR'), ('Operations', 'CEO'), ('Cashiers', 'Cashier'), ('Executive', 'Exe')], default='MALE', max_length=20)),
                ('Duties', models.TextField(default='ICT', max_length=1000)),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='MALE', max_length=7)),
                ('Contact', models.CharField(default='Tel or Email', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 2, 17, 15, 23, 15, 252264, tzinfo=utc))),
                ('PaymentMadeTo', models.CharField(default='Canon', max_length=100)),
                ('ReasonForPayment', models.TextField(default='Only relatively small expense', max_length=25)),
                ('Amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='salary',
            name='Staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.StaffDetails'),
        ),
    ]
