# Generated by Django 2.2.8 on 2020-09-24 12:47

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name='tenant name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpensesReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('Name', models.CharField(default='Name', max_length=100, null=True)),
                ('Amount', models.FloatField(default=0.0, null=True)),
                ('Reason', models.CharField(max_length=100, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('DayOfTheWeek', models.CharField(max_length=100)),
                ('TotalOffering', models.IntegerField(default=0)),
                ('AmountInWords', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfferingsReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('Day', models.CharField(max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pledges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('DayOfTheWeek', models.CharField(max_length=100)),
                ('PledgeMadeBy', models.CharField(max_length=100)),
                ('Reason', models.CharField(max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PledgesReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Day', models.CharField(max_length=100, null=True)),
                ('Reason', models.CharField(max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=12)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalaryReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('Staff', models.CharField(max_length=100, null=True)),
                ('Month', models.CharField(max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('PaymentMadeTo', models.CharField(max_length=100)),
                ('ReasonForPayment', models.CharField(choices=[('Mechanic', 'Car Repairing'), ('WaterBills', 'Water Bills'), ('Electricity', 'Electricity Bills'), ('URA', 'Paying Revenue')], max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('image', models.ImageField(default='Photo', upload_to='media')),
                ('FistName', models.CharField(max_length=150)),
                ('SecondName', models.CharField(max_length=150)),
                ('Salary', models.IntegerField(default=0)),
                ('Role', models.CharField(default='MALE', max_length=20)),
                ('Duties', models.CharField(max_length=1000)),
                ('Sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='MALE', max_length=7)),
                ('Contact', models.CharField(default='Tel or Email', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sundry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('PaymentMadeTo', models.CharField(max_length=100)),
                ('ReasonForPayment', models.CharField(max_length=250)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SundryReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('Name', models.CharField(default='Name', max_length=100, null=True)),
                ('Amount', models.FloatField(default=0.0, null=True)),
                ('Reason', models.CharField(max_length=100, null=True)),
                ('month', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tithes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('DayOfTheWeek', models.CharField(max_length=100)),
                ('TitheMadeBy', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TithesReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Day', models.CharField(max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
