# Generated by Django 2.1.5 on 2019-02-20 10:13

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0002_auto_20190217_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
                ('Amount', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 10, 13, 22, 579990, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 10, 13, 22, 580487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 10, 13, 22, 580487, tzinfo=utc)),
        ),
    ]
