# Generated by Django 2.1.5 on 2019-02-20 10:38

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0003_auto_20190220_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
                ('Amount', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.CreateModel(
            name='SundryArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=200)),
                ('Amount', models.IntegerField(verbose_name=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Archive',
            new_name='ExpenditureArchive',
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 10, 38, 11, 390417, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 10, 38, 11, 391410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 10, 38, 11, 390914, tzinfo=utc)),
        ),
    ]
