# Generated by Django 2.1.5 on 2019-02-20 13:27

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0004_auto_20190220_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=300)),
                ('Name', models.CharField(max_length=300)),
                ('Amount', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='ExpenditureArchive',
        ),
        migrations.DeleteModel(
            name='SalaryArchive',
        ),
        migrations.DeleteModel(
            name='SundryArchive',
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 13, 27, 5, 870869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 13, 27, 5, 871826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 20, 13, 27, 5, 871394, tzinfo=utc)),
        ),
    ]
