# Generated by Django 2.1.5 on 2019-02-21 06:37

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0005_auto_20190220_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpensesArchive',
        ),
        migrations.AddField(
            model_name='salary',
            name='Figures',
            field=models.CharField(default='amount in words', max_length=500),
        ),
        migrations.AddField(
            model_name='spend',
            name='Figures',
            field=models.CharField(default='amount in words', max_length=500),
        ),
        migrations.AddField(
            model_name='sundry',
            name='Figures',
            field=models.CharField(default='amount in words', max_length=500),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 21, 6, 37, 23, 66258, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='ApprovedBy',
            field=models.CharField(default='Manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 21, 6, 37, 23, 67254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='ReceivedBy',
            field=models.CharField(default='Receiptionist', max_length=100),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 2, 21, 6, 37, 23, 66258, tzinfo=utc)),
        ),
    ]
