# Generated by Django 2.1.7 on 2019-03-01 05:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190228_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesExecutiveReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=50)),
                ('PaymentMadeTo', models.CharField(max_length=100)),
                ('ReasonForPayment', models.CharField(max_length=200)),
                ('Amount', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 5, 14, 2, 607153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 5, 14, 2, 607153, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 5, 14, 2, 607153, tzinfo=utc)),
        ),
    ]
