# Generated by Django 2.1.7 on 2019-03-01 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190301_0814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpensesExecutiveReport',
        ),
        migrations.AddField(
            model_name='staffdetails',
            name='image',
            field=models.ImageField(default='Photo', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 8, 18, 15, 601286, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 8, 18, 15, 602763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 1, 8, 18, 15, 602763, tzinfo=utc)),
        ),
    ]
