# Generated by Django 2.1.7 on 2019-03-06 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190301_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 3, 6, 7, 28, 37, 833995, tzinfo=utc))),
                ('Name', models.CharField(default='Name', max_length=100, null=True)),
                ('Amount', models.FloatField(default=0.0, null=True)),
                ('Reason', models.CharField(default='Reason', max_length=10000)),
                ('Month', models.CharField(default='month', max_length=100)),
                ('Year', models.CharField(default='year', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 7, 28, 37, 828717, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 7, 28, 37, 833995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 7, 28, 37, 832997, tzinfo=utc)),
        ),
    ]
