# Generated by Django 2.1.7 on 2019-03-06 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190306_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesreport',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 12, 4, 36, 979626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 12, 4, 36, 979626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 12, 4, 36, 979626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 12, 4, 36, 979626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 12, 4, 36, 979626, tzinfo=utc)),
        ),
    ]
