# Generated by Django 2.1.7 on 2019-03-06 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190306_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesreport',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 13, 35, 59, 887033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 13, 35, 59, 887033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 13, 35, 59, 887033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 13, 35, 59, 887033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 6, 13, 35, 59, 887033, tzinfo=utc)),
        ),
    ]
