# Generated by Django 2.1.7 on 2019-03-09 05:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190306_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesreport',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 9, 5, 31, 44, 903370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 9, 5, 31, 44, 903370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 9, 5, 31, 44, 898372, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='AmountInWords',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='spend',
            name='ApprovedBy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 9, 5, 31, 44, 903370, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='ReceivedBy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 3, 9, 5, 31, 44, 903370, tzinfo=utc)),
        ),
    ]
