# Generated by Django 2.1.7 on 2019-04-24 15:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20190312_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='Salary_Type',
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 15, 55, 36, 620454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='AmountInWords',
            field=models.CharField(default='amount in words', max_length=500),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 15, 55, 36, 620454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=12),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Staff',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 15, 55, 36, 624487, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 15, 55, 36, 620454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='AmountInWords',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 15, 55, 36, 620454, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 15, 55, 36, 624487, tzinfo=utc)),
        ),
    ]
