# Generated by Django 2.1.7 on 2019-04-24 16:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20190424_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='Staff',
            new_name='Name',
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 5, 43, 769619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='AmountInWords',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 5, 43, 769619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 5, 43, 769619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 5, 43, 769619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 5, 43, 769619, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='PaymentMadeTo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='ReasonForPayment',
            field=models.TextField(default='Only very small expenses', max_length=25),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 5, 43, 769619, tzinfo=utc)),
        ),
    ]
