# Generated by Django 2.1.7 on 2019-04-24 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20190424_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='ApprovedBy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 34, 12, 343337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='ReceivedBy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 34, 12, 343337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 34, 12, 343337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='AmountInWords',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 34, 12, 343337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Duties',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='FistName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='Role',
            field=models.CharField(default='MALE', max_length=20),
        ),
        migrations.AlterField(
            model_name='staffdetails',
            name='SecondName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 34, 12, 343337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='ReasonForPayment',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='ApprovedBy',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 34, 12, 343337, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='ReceivedBy',
            field=models.CharField(max_length=100),
        ),
    ]
