# Generated by Django 2.1.7 on 2019-04-24 16:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20190424_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesreportarchive',
            name='ApprovedBy',
        ),
        migrations.RemoveField(
            model_name='expensesreportarchive',
            name='ReceivedBy',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='ApprovedBy',
        ),
        migrations.RemoveField(
            model_name='spend',
            name='ReceivedBy',
        ),
        migrations.RemoveField(
            model_name='sundryreportarchive',
            name='ApprovedBy',
        ),
        migrations.RemoveField(
            model_name='sundryreportarchive',
            name='ReceivedBy',
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 47, 11, 453282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 47, 11, 453282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 47, 11, 453282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 47, 11, 453282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 47, 11, 453282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 47, 11, 453282, tzinfo=utc)),
        ),
    ]
