# Generated by Django 2.1.7 on 2019-04-24 16:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20190424_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 48, 50, 359610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 48, 50, 359610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 48, 50, 359610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 48, 50, 359610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='PaymentMadeTo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 48, 50, 359610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 24, 16, 48, 50, 359610, tzinfo=utc)),
        ),
    ]
