# Generated by Django 2.1.7 on 2019-04-25 15:46

import datetime
import django.contrib.admin.widgets
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20190424_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 4, 25, 15, 46, 3, 913955, tzinfo=utc))),
                ('DayOfTheWeek', models.DateField(verbose_name=django.contrib.admin.widgets.AdminDateWidget)),
                ('TotalOffering', models.IntegerField(default=0)),
                ('AmountInWords', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pledges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 4, 25, 15, 46, 3, 914903, tzinfo=utc))),
                ('DayOfTheWeek', models.DateField(verbose_name=django.contrib.admin.widgets.AdminDateWidget)),
                ('PledgeMadeBy', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Tithes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 4, 25, 15, 46, 3, 913955, tzinfo=utc))),
                ('DayOfTheWeek', models.DateField(verbose_name=django.contrib.admin.widgets.AdminDateWidget)),
                ('TitheMadeBy', models.CharField(max_length=100)),
                ('Amount', models.IntegerField(default=0)),
                ('AmountInWords', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 15, 46, 3, 915938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 15, 46, 3, 912953, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 15, 46, 3, 915938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 15, 46, 3, 914903, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 15, 46, 3, 913955, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 15, 46, 3, 915938, tzinfo=utc)),
        ),
    ]
