# Generated by Django 2.1.7 on 2019-04-25 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20190425_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferingsReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 311131, tzinfo=utc))),
                ('Day', models.CharField(max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PledgesReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 312082, tzinfo=utc))),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Day', models.CharField(max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TithesReportArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 311131, tzinfo=utc))),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Day', models.CharField(max_length=100, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('archivedmonth', models.CharField(max_length=100, null=True)),
                ('archivedyear', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 309179, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 308236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 308236, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 307229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 310288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 309179, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 307229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 310288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tithes',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 17, 8, 44, 308236, tzinfo=utc)),
        ),
    ]
