# Generated by Django 2.1.7 on 2019-04-26 06:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20190425_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledges',
            name='Reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pledgesreportarchive',
            name='Reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offerings',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='offeringsreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledges',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pledgesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='salaryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='spend',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundry',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sundryreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tithes',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tithesreportarchive',
            name='Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 6, 32, 58, 756658, tzinfo=utc)),
        ),
    ]
